/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: { extend: {} },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      // 1. VAYU NIGHT — default dark glassmorphic (custom)
      {
        'vayu-night': {
          'primary':          '#00e5ff',
          'primary-content':  '#030509',
          'secondary':        '#76ff03',
          'secondary-content':'#030509',
          'accent':           '#ff6d00',
          'accent-content':   '#ffffff',
          'neutral':          '#0e1623',
          'neutral-content':  '#f0f6fc',
          'base-100':         '#04060c',
          'base-200':         '#090e17',
          'base-300':         '#0e1623',
          'base-content':     '#f0f6fc',
          'info':             '#00b4cc',
          'success':          '#00e676',
          'warning':          '#ffea00',
          'error':            '#d50000',
        },
      },
      // 2. SOLAR FLARE — warm orange/red dark
      {
        'solar-flare': {
          'primary':          '#ff6f00',
          'primary-content':  '#ffffff',
          'secondary':        '#ff1744',
          'secondary-content':'#ffffff',
          'accent':           '#ffd600',
          'accent-content':   '#1a0500',
          'neutral':          '#1a0d00',
          'neutral-content':  '#fff3e0',
          'base-100':         '#0d0500',
          'base-200':         '#1a0d00',
          'base-300':         '#2a1500',
          'base-content':     '#fff3e0',
          'info':             '#ff8f00',
          'success':          '#76ff03',
          'warning':          '#ffd600',
          'error':            '#ff1744',
        },
      },
      // 3. ARCTIC PULSE — cool blue/white light theme
      {
        'arctic-pulse': {
          'primary':          '#0ea5e9',
          'primary-content':  '#ffffff',
          'secondary':        '#6366f1',
          'secondary-content':'#ffffff',
          'accent':           '#22d3ee',
          'accent-content':   '#0a1628',
          'neutral':          '#1e3a5f',
          'neutral-content':  '#f0f9ff',
          'base-100':         '#f0f9ff',
          'base-200':         '#e0f2fe',
          'base-300':         '#bae6fd',
          'base-content':     '#0c2d4e',
          'info':             '#0ea5e9',
          'success':          '#10b981',
          'warning':          '#f59e0b',
          'error':            '#ef4444',
        },
      },
      // 4. FOREST GUARDIAN — deep green environmental
      {
        'forest-guardian': {
          'primary':          '#00e676',
          'primary-content':  '#001a0a',
          'secondary':        '#69f0ae',
          'secondary-content':'#001a0a',
          'accent':           '#64dd17',
          'accent-content':   '#001a0a',
          'neutral':          '#0a1f0d',
          'neutral-content':  '#e8f5e9',
          'base-100':         '#050f07',
          'base-200':         '#0a1f0d',
          'base-300':         '#122917',
          'base-content':     '#e8f5e9',
          'info':             '#00bcd4',
          'success':          '#00e676',
          'warning':          '#ffea00',
          'error':            '#ff5252',
        },
      },
    ],
    darkTheme: 'vayu-night',
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
};
